{
    "module": "models",
    "class_name": "LSTMModule",
    "config": {
        "name": "lstm_module",
        "trainable": True,
        "dtype": {
            "module": "keras",
            "class_name": "DTypePolicy",
            "config": {"name": "float32"},
            "registered_name": None,
            "shared_object_id": 123335988418640,
        },
        "configs": {
            "exp_name": "NAB",
            "dataset": "NSV_sub_right_sub_4374",
            "y_scale": 5,
            "one_image": 0,
            "l_seq": 12,
            "l_win": 24,
            "n_channel": 1,
            "TRAIN_VAE": 1,
            "TRAIN_LSTM": 1,
            "TRAIN_sigma": 0,
            "batch_size": 32,
            "batch_size_lstm": 32,
            "load_model": 1,
            "load_dir": "default",
            "num_epochs_vae": 0,
            "num_epochs_lstm": 20,
            "learning_rate_vae": 0.0004,
            "learning_rate_lstm": 0.0002,
            "code_size": 6,
            "sigma": 0.1,
            "sigma2_offset": 0.01,
            "num_hidden_units": 512,
            "num_hidden_units_lstm": 64,
        },
    },
    "registered_name": "LSTMModule",
    "build_config": {"input_shape": [1, 11, 6]},
}
